# Generated by Django 3.0.14 on 2023-12-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair_collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
