# Generated by Django 5.0 on 2023-12-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair_collection', '0006_resulthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultHistory',
        ),
    ]
